[connections.pg]
url = "postgresql://postgres:postgres@localhost:2345/test"

[connections.mysql]
url = "mysql://root:root@localhost:6033/TEST"

[connections.sqlite]
url = "sqlite:///sqlite/test.sqlite"

[connections.supabase]
SUPABASE_URL = "https://<myprojecturl>.supabase.co"
SUPABASE_KEY = "<mykey>"